easy_admin:
    site_name: "Pizza's Toro"
    design:
      menu:
        - { label: 'Homepage', route: 'main' }
        - Ingredient
        - Pizza
    entities:
        Ingredient:
          class: App\Entity\Ingredient
          form:
            fields:
              - 'name'
              - 'price'
        Pizza:
          class: App\Entity\Pizza
          form:
            fields:
              - 'name'
              - 'ingredients'