version: "3.0"
services:
  web:
    image: nginx:alpine
    container_name: pizza_web
    working_dir: /application
    volumes:
      - .:/application
      - ./environment/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8080:80"

  php:
    image: recchia/php-fpm
    container_name: pizza_php
    working_dir: /application
    volumes:
      - .:/application

  database:
    image: mysql:5.7
    container_name: pizza_db
    volumes:
      - "${HOME}/${USER}/dockerdata/pizza:/var/lib/mysql"
    environment:
      - MYSQL_ROOT_PASSWORD=pizza
      - MYSQL_DATABASE=pizza
      - MYSQL_USER=pizza
      - MYSQL_PASSWORD=pizza
    ports:
      - "3306:3306"

  blackfire:
    container_name: pizza_blackfire
    image: blackfire/blackfire
    environment:
      - BLACKFIRE_SERVER_ID
      - BLACKFIRE_SERVER_TOKEN